// occupation_tags.data.mjs —— 职业库补标数据（AI 全量初标）
// 三组标签：environment_tags（六维环境）、typical_seniority（职级门槛）、credential_required（资格要求）
// 向量顺序: [noise, interruption, communication_mode, rule_clarity, remote_feasibility, travel, seniority, credential, tag_confidence]
// 枚举：noise/interruption/remote ∈ low|medium|high；comm ∈ written|mostly_written|mixed|mostly_verbal|verbal；
//       rule ∈ high|medium|low；travel ∈ none|rare|occasional|frequent；
//       seniority ∈ entry_friendly|entry_possible|experienced_required；
//       credential ∈ none|medical_license|law_license|teaching_cert|cpa_professional|driver_license|vocational_cert|other_professional
// 人工修正：直接改 MAP/OVERRIDES 后重跑 tag_occupations.mjs 即可。

export const CAT = {
  software_dev:      ["low", "low", "mostly_written", "high", "high", "none", "entry_friendly", "none", "high"],
  data_analysis:     ["low", "low", "mostly_written", "high", "high", "none", "entry_friendly", "none", "high"],
  it_ops:            ["medium", "medium", "mixed", "high", "medium", "rare", "entry_possible", "vocational_cert", "medium"],
  engineering_rd:    ["medium", "low", "mostly_written", "high", "medium", "rare", "entry_possible", "none", "medium"],
  field_engineer:    ["high", "high", "mixed", "medium", "low", "occasional", "entry_possible", "vocational_cert", "medium"],
  technician_repair: ["high", "medium", "mostly_verbal", "medium", "low", "rare", "entry_friendly", "vocational_cert", "medium"],
  operator_production: ["high", "medium", "mostly_verbal", "high", "low", "none", "entry_friendly", "vocational_cert", "medium"],
  driver:            ["high", "medium", "mostly_verbal", "high", "low", "frequent", "entry_friendly", "driver_license", "high"],
  logistics_warehouse: ["high", "medium", "mixed", "high", "low", "none", "entry_friendly", "none", "medium"],
  sales:             ["medium", "high", "verbal", "low", "low", "occasional", "entry_friendly", "none", "high"],
  customer_service:  ["medium", "high", "mostly_verbal", "medium", "medium", "none", "entry_friendly", "none", "medium"],
  retail_clerk:      ["medium", "high", "mostly_verbal", "medium", "low", "none", "entry_friendly", "none", "high"],
  marketing_ops:     ["medium", "medium", "mixed", "medium", "medium", "rare", "entry_possible", "none", "medium"],
  pr_media_journalist: ["high", "high", "mostly_verbal", "low", "low", "occasional", "experienced_required", "none", "medium"],
  content_writing:   ["low", "low", "written", "medium", "high", "rare", "entry_friendly", "none", "high"],
  design_creative:   ["low", "low", "mostly_written", "medium", "high", "rare", "entry_friendly", "none", "high"],
  research_academic: ["low", "low", "mostly_written", "medium", "medium", "occasional", "experienced_required", "none", "high"],
  research_assistant: ["low", "low", "mostly_written", "high", "medium", "rare", "entry_friendly", "none", "high"],
  finance_accounting: ["low", "low", "mostly_written", "high", "medium", "occasional", "entry_possible", "cpa_professional", "medium"],
  finance_analyst:   ["medium", "medium", "mostly_written", "high", "medium", "rare", "experienced_required", "cpa_professional", "medium"],
  finance_sales:     ["medium", "high", "verbal", "medium", "low", "rare", "entry_friendly", "vocational_cert", "medium"],
  banking_clerk:     ["medium", "high", "mostly_verbal", "high", "low", "none", "entry_friendly", "vocational_cert", "medium"],
  hr_admin:          ["medium", "medium", "mixed", "medium", "medium", "none", "entry_friendly", "none", "high"],
  legal:             ["low", "medium", "mostly_written", "high", "medium", "rare", "experienced_required", "law_license", "high"],
  medical_clinical:  ["high", "high", "mostly_verbal", "medium", "low", "none", "experienced_required", "medical_license", "high"],
  medical_support:   ["high", "high", "mostly_verbal", "medium", "low", "none", "entry_possible", "vocational_cert", "medium"],
  teaching:          ["medium", "medium", "mostly_verbal", "medium", "low", "none", "entry_possible", "teaching_cert", "high"],
  childcare:         ["high", "high", "verbal", "low", "low", "none", "entry_friendly", "teaching_cert", "medium"],
  counseling:        ["low", "medium", "mostly_verbal", "low", "medium", "none", "entry_possible", "vocational_cert", "medium"],
  hospitality:       ["high", "high", "verbal", "low", "low", "none", "entry_friendly", "vocational_cert", "high"],
  skilled_trade:     ["high", "medium", "mostly_verbal", "medium", "low", "none", "entry_friendly", "vocational_cert", "medium"],
  security_emergency: ["high", "high", "mostly_verbal", "medium", "low", "occasional", "entry_possible", "vocational_cert", "low"],
  performance_art:   ["high", "high", "verbal", "low", "medium", "frequent", "experienced_required", "none", "medium"],
  media_production:  ["medium", "medium", "mixed", "medium", "medium", "occasional", "entry_possible", "none", "medium"],
  management:        ["medium", "high", "mostly_verbal", "low", "medium", "frequent", "experienced_required", "none", "medium"],
  pm_product:        ["medium", "high", "mixed", "low", "medium", "rare", "entry_possible", "none", "medium"],
  agriculture:       ["high", "low", "mostly_verbal", "medium", "low", "none", "entry_friendly", "none", "medium"],
  librarian_archive: ["low", "low", "mostly_written", "high", "medium", "none", "entry_friendly", "none", "high"],
  lab_tech:          ["medium", "low", "mostly_written", "high", "low", "none", "entry_friendly", "vocational_cert", "high"],
  aviation:          ["high", "high", "mostly_verbal", "high", "low", "frequent", "experienced_required", "vocational_cert", "high"],
  civil_service:     ["medium", "medium", "mostly_written", "high", "low", "rare", "entry_possible", "vocational_cert", "medium"],
  consulting:        ["medium", "medium", "mixed", "low", "medium", "occasional", "experienced_required", "none", "medium"],
  tourism:           ["medium", "high", "verbal", "low", "low", "frequent", "entry_friendly", "none", "medium"],
  general_labor:     ["high", "medium", "mostly_verbal", "medium", "low", "none", "entry_friendly", "none", "low"],
  generic:           ["medium", "medium", "mixed", "medium", "medium", "none", "unknown", "none", "low"],
};

export const OVERRIDES = {
  // 资格修正
  "兽医": { credential_required: "other_professional" },
  "兽医/宠物洗护": { credential_required: "other_professional" },
  "药剂师": { credential_required: "other_professional" },
  "药剂师或药房技术员": { credential_required: "other_professional" },
  "助产士": { credential_required: "other_professional", seniority: "experienced_required" },
  "急救医护人员": { credential_required: "medical_license" },
  "法官": { seniority: "experienced_required" },
  // 心理类高级职位：需系统训练/学位，应届不可入
  "心理学家": { seniority: "experienced_required", tag_confidence: "medium" },
  "司法心理学家": { seniority: "experienced_required", tag_confidence: "medium" },
  "临床心理学家": { seniority: "experienced_required", tag_confidence: "medium" },
  "学校心理学家": { seniority: "experienced_required", tag_confidence: "medium" },
  "儿童心理学家": { seniority: "experienced_required", tag_confidence: "medium" },
  "精神分析师": { seniority: "experienced_required", credential_required: "medical_license", tag_confidence: "medium" },
  "心理治疗师": { credential_required: "other_professional", tag_confidence: "medium" },
  // 环境修正（个别与类别默认差异大的职业）
  "地质学家": { env: { noise_level: "medium", interruption_frequency: "low", communication_mode: "mostly_written", rule_clarity: "medium", remote_feasibility: "low", travel_level: "occasional" }, tag_confidence: "medium" },
  "考古学家": { env: { noise_level: "medium", remote_feasibility: "low", travel_level: "occasional" }, tag_confidence: "medium" },
  "考古学": { env: { noise_level: "medium", remote_feasibility: "low", travel_level: "occasional" }, tag_confidence: "medium" },
  "野生动物生物学家": { env: { remote_feasibility: "low", travel_level: "occasional" }, tag_confidence: "medium" },
  "护林员": { env: { noise_level: "low", interruption_frequency: "low" }, tag_confidence: "medium" },
  "电台主播": { env: { noise_level: "medium" }, tag_confidence: "medium" },
  "新闻主播": { env: { noise_level: "medium" }, tag_confidence: "medium" },
  "消防员": { env: { noise_level: "high", interruption_frequency: "high" }, tag_confidence: "low" },
};

export const MAP = {
  // A–B
  "埃及学家": "research_academic", "安检员": "security_emergency", "安全/质量员（工地）": "field_engineer",
  "安全员/质检员/化验员": "lab_tech", "安装人员/巡检维修人员（大型设备）": "technician_repair",
  "按摩养生技师": "hospitality", "按摩治疗师": "medical_support", "办公室/文员": "hr_admin", "办公室经理": "management",
  "办公室职员": "hr_admin", "办公室主任": "management", "办公室助理": "hr_admin", "办事员": "hr_admin",
  "保安/保洁/司机/搬运工/叉车工": "general_labor", "保姆": "hospitality", "保险产品设计": "finance_analyst",
  "保险代理人": "finance_sales", "保险代理人/医托/星探（个人中介）": "finance_sales", "保险行业": "generic",
  "保险业务员": "finance_sales", "报社/出版社/电视台（新闻事业编）": "content_writing", "编导/策划": "pm_product",
  "编辑": "content_writing", "编辑/音乐治疗师": "content_writing", "编剧": "content_writing",
  "编剧/微生物学家": "content_writing", "编舞师": "performance_art", "编舞师/舞台美术": "performance_art",
  "表演策划/导演/现场执行": "performance_art", "表演艺术行业": "generic", "表演者": "performance_art",
  "表演艺术从业者": "performance_art",
  "殡仪师": "hospitality", "殡葬师": "hospitality", "病虫害防治员/兽医": "agriculture", "病毒学家": "research_academic",
  "播音员": "performance_art", "博物馆策展人": "librarian_archive", "财务分析": "finance_accounting",
  "财务规划师": "finance_sales", "财务经理": "management", "裁缝/珠宝设计师": "skilled_trade", "裁判/解说": "performance_art",
  "采购": "logistics_warehouse", "采购/物资管理": "logistics_warehouse", "采购员": "logistics_warehouse",
  "餐厅老板": "management", "测量师/勘察工程师/岩土工程师/勘探工程师": "field_engineer",
  "测量员/资料员/试验员": "field_engineer", "测试": "software_dev", "策划编辑": "content_writing",
  "策展人": "librarian_archive", "策展人/陈列部": "librarian_archive", "插画/封面设计": "design_creative",
  "插画师": "design_creative", "产品经理（含游戏策划、影视制片人、统筹）": "pm_product", "产品经理/需求分析师": "pm_product",
  "场地设备维护/农机驾驶员/船工/采摘打捞工人": "agriculture", "场控": "media_production", "场务（后勤）": "general_labor",
  "唱片店老板": "management", "唱片店老板或店员": "retail_clerk", "唱片骑师（DJ）": "performance_art",
  "唱片制作人": "media_production", "抄表员/稽查/用户服务": "technician_repair", "陈列设计师": "design_creative",
  "承揽（投行拉业务）": "finance_sales", "承销（兜售债券股票）": "finance_sales", "承做（IPO材料）": "finance_analyst",
  "乘务员/安全员": "aviation", "程序员": "software_dev", "出版人": "management",
  "出品人/制片人（影视项目经理）": "pm_product", "厨师": "skilled_trade", "厨师/配菜师": "skilled_trade",
  "穿洞师": "skilled_trade", "传菜员/服务员/前台": "hospitality", "传教士": "counseling", "传媒行业": "generic",
  "创业者": "management", "创意总监": "management", "词曲作者": "content_writing",
  "词曲作者/混音师/录音师/乐手": "media_production", "大客户销售/大客户经理": "sales", "大使": "civil_service",
  "大学教授": "research_academic", "档案管理员": "librarian_archive", "导演": "performance_art",
  "地接/导游/领队/讲解员": "tourism", "地质学家": "research_academic", "灯光/摄影摄像/现场录音": "media_production",
  "电工": "technician_repair", "电脑动画师": "design_creative", "电脑技术员": "it_ops",
  "电脑维修技术员": "technician_repair", "电气工程师": "engineering_rd", "电商美工": "design_creative",
  "电视行业": "generic", "电视制片人": "pm_product", "电台主播": "performance_art", "电台DJ": "performance_art",
  "电影导演": "performance_art", "电影剪辑师": "media_production", "电影明星": "performance_art",
  "电影摄影师": "media_production", "电影制片人": "pm_product", "电影制作人": "pm_product",
  "电子游戏设计师": "design_creative", "店铺运营": "marketing_ops", "店员": "retail_clerk", "店主": "management",
  "调度员（电力/供水/生产）": "operator_production", "调酒师": "hospitality", "动捕演员": "performance_art",
  "动画师": "design_creative", "动画师/原画/建模（2D/3D）": "design_creative", "动物学家": "research_academic",
  "动物园饲养员": "agriculture", "独裁者": "management", "短视频编导/拍摄/剪辑": "media_production",
  "儿科护士": "medical_clinical", "儿科医生": "medical_clinical", "儿童保育员": "childcare",
  "儿童教育工作者": "teaching", "儿童心理学家": "counseling", "发行/市场营销（图书）": "marketing_ops",
  "发行/宣传/商务（影视）": "marketing_ops", "发行引入/研发对接": "marketing_ops", "发型师": "hospitality",
  // C–F
  "法官": "legal", "法官/检察官": "legal", "法务": "legal", "法务秘书": "legal", "法医": "medical_clinical",
  "法医病理学家": "medical_clinical", "法医人类学家": "medical_clinical", "房产中介": "sales",
  "房产中介/留学中介/红娘": "sales", "房地产投资人": "management", "房地产投资人/建筑师": "management",
  "房地产行业从业者": "generic", "房地产营销策划（市场/文案/广告/销售策划）": "marketing_ops", "飞行员": "aviation",
  "非营利组织": "generic", "分析师": "data_analysis", "风控/合规": "finance_analyst", "服务员": "hospitality",
  "服装化妆道具团队": "media_production", "服装设计师": "design_creative", "副导演/执行导演/统筹/场记": "media_production",
  "高管": "management", "高管助理": "hr_admin", "高中教师": "teaching", "高中历史老师": "teaching",
  "高中英语老师": "teaching", "糕点师": "skilled_trade", "歌手": "performance_art",
  "各类司机（公交/地铁/火车）": "driver", "工程部/计划建设部（甲方管理）": "management",
  "工程技术施工员": "field_engineer", "工程师": "engineering_rd", "工业工程师": "engineering_rd",
  "工业设计师": "design_creative", "工艺工程师（水厂/污水处理）": "engineering_rd", "工艺工程师/操作工人": "engineering_rd",
  "公安/民警": "security_emergency", "公共卫生行业": "generic", "公共卫生专家": "research_academic",
  "公关/品牌公关": "pr_media_journalist", "公关经理": "pr_media_journalist", "公关专员": "pr_media_journalist",
  "公司律师": "legal", "公务员": "civil_service", "公务员——办公室/党委办（写材料、协调）": "civil_service",
  "公务员——宣传部/统战部（对外联络）": "civil_service", "公务员——政法委/纪委监委（监督执纪）": "civil_service",
  "公务员——组织部（干部管理）": "civil_service", "供应链管理": "management",
  "供应链专员/商家运营（旅行社）": "marketing_ops", "古生物学家": "research_academic", "股票经纪人": "finance_sales",
  "鼓手": "performance_art", "顾问": "consulting", "雇佣兵": "security_emergency", "管理咨询顾问": "consulting",
  "广播剧策划/导演/监制": "pm_product", "广播新闻记者": "pr_media_journalist", "广告创意/文案策划": "content_writing",
  "广告从业者": "generic", "广告客户执行/客户经理": "sales", "广告业": "generic", "广告总监": "management",
  "国际关系专家": "research_academic", "国际间谍": "security_emergency", "国际商务专家": "consulting",
  "海洋生物学家": "research_academic", "航空航天工程师": "engineering_rd", "核工程师": "engineering_rd",
  "后勤（保安/保洁/司机/维修工/仓库）": "general_labor", "护林员": "agriculture", "护士": "medical_clinical",
  "花艺师": "skilled_trade", "化学工程师": "engineering_rd", "化学家": "research_academic",
  "化学老师": "teaching", "化妆师": "hospitality", "画家": "design_creative", "环保主义者": "generic",
  "环境工程师": "engineering_rd", "环境工程师/GIS专家": "engineering_rd", "环境科学家": "research_academic",
  "会计/财务/审计": "finance_accounting", "会计师": "finance_accounting", "会计师/审计（事务所）": "finance_accounting",
  "婚庆策划": "pm_product", "婚庆策划师": "pm_product", "活动策划师": "pm_product", "活动协调员": "pm_product",
  "活动运营/广告投放": "marketing_ops", "货代跟单员": "logistics_warehouse", "货代业务员": "sales",
  "机械工程师": "engineering_rd", "机械维修工": "technician_repair", "基金经理/交易策略": "finance_analyst",
  "吉他手": "performance_art", "急救医护人员": "medical_support", "急救医疗技术员": "medical_support",
  "计调/操作员（订票订车订房）": "tourism", "计费/数据分析（IT部门）": "data_analysis",
  "计划调度员/运控中心": "operator_production", "计算机工程师": "software_dev", "计算机顾问": "consulting",
  "计算机科学家": "research_academic", "计算机行业": "generic", "记者": "pr_media_journalist",
  "记者/记者型主持": "pr_media_journalist", "技术文档撰写人": "content_writing", "技术研发": "engineering_rd",
  "技术员": "it_ops", "家庭主妇/主夫": "general_labor", "家政保洁": "general_labor",
  "家政保洁/代驾/出租车司机": "driver", "家装设计师": "design_creative",
  "甲方工程部/基建处工程师（工程管理）": "field_engineer", "监理": "field_engineer", "监制": "pm_product",
  "剪辑后期/特效": "media_production", "检测工程师/质量监督员": "lab_tech", "建筑工人": "general_labor",
  "建筑设计师/结构设计师/给排水暖通电气设计师": "engineering_rd", "建筑师": "engineering_rd",
  "健康教育工作者": "teaching", "交通工具检查维修人员": "technician_repair", "教练": "teaching",
  "教练（运动/健身）": "teaching", "教师": "teaching", "教师（各层级）/教务": "teaching",
  "教师（学校事业单位）": "teaching", "教育工作者": "teaching", "洁牙师": "medical_support",
  "金融产品经理": "finance_analyst", "金融分析师": "finance_analyst", "经济学家": "research_academic",
  "经理": "management", "经理/主管/副总经理": "management", "精品投行（FA）/尾货中介/招标代理": "finance_sales",
  "精神分析师": "counseling", "精神科医生": "medical_clinical", "精算师": "finance_analyst",
  "景观设计师/效果图设计师": "design_creative", "景区活动策划/文案/新媒体运营": "marketing_ops",
  "警察": "security_emergency", "酒吧老板": "management", "酒店服务人员": "hospitality", "酒店经理": "management",
  "救生员": "security_emergency", "剧作家": "content_writing", "军队职业": "security_emergency",
  "军队职员": "security_emergency", "卡车司机": "driver",
  "开发工程师": "software_dev", "考古学": "research_academic", "考古学家": "research_academic",
  "科学家": "research_academic", "科研院所研究人员": "research_academic", "客服": "customer_service",
  "客服代表": "customer_service", "客服人员": "customer_service", "客户服务部": "customer_service",
  "客户经理（银行/证券开户）": "finance_sales", "空乘人员": "aviation", "库存管理/仓储/发货": "logistics_warehouse",
  "矿工（设备操作）": "operator_production", "揽收员/配送员/分拣员": "logistics_warehouse",
  "理财顾问": "finance_sales", "理货师": "logistics_warehouse", "理疗师": "medical_support",
  "历史学家": "research_academic", "历史学教授": "research_academic", "量化研发": "finance_analyst",
  "猎头/艺人经纪人/达人中介/MCN经纪人": "sales", "临床心理学家": "counseling", "零售店员": "retail_clerk",
  "领队/经纪人": "tourism", "录音工程师": "media_production", "旅行作家": "content_writing",
  "旅游产品设计师": "tourism", "旅游规划师/旅行体验师/课程顾问/理财规划师（换名的销售）": "sales",
  "旅游规划师/旅游定制师（销售）": "sales", "律师": "legal", "买量/广告投放": "marketing_ops",
  "漫画绘制师": "design_creative", "漫画家": "design_creative", "媒介策划/媒介拓展": "marketing_ops",
  "美发师": "hospitality", "美容美发师": "hospitality", "美容师": "hospitality", "美术老师": "teaching",
  "美术指导/视觉设计": "design_creative", "秘书": "hr_admin", "秘书/助理": "hr_admin", "面包师": "skilled_trade",
  "模特": "performance_art", "木匠": "skilled_trade", "募捐专员": "sales", "拍卖业务员/拍卖品管理": "sales",
  "拍卖主持人": "performance_art", "培训讲师": "teaching", "培训师": "teaching", "配音演员（CV）": "performance_art",
  "批发/经销商业务员": "sales", "票务管理/售票/验票": "customer_service", "平面美术师": "design_creative",
  "平面设计师": "design_creative", "企业管理人员": "management", "企业主": "management",
  "气象专家": "research_academic", "汽车技术员": "technician_repair", "汽车维修工": "technician_repair",
  "前后端开发/架构师/网络安全工程师": "software_dev", "前台接待": "customer_service", "青年牧师": "counseling",
  "渠道运营/营业厅": "marketing_ops", "全职父母": "general_labor", "人大/政协/群团（较清闲机关）": "civil_service",
  "人类学家": "research_academic", "人力资源专员": "hr_admin", "人事/人力资源": "hr_admin",
  // S–Z
  "软件工程师": "software_dev", "软件开发工程师": "software_dev", "软件设计师": "software_dev",
  "赛车手": "performance_art", "赛事/演出组织策划经理": "pm_product", "商人": "management",
  "商务（拉赞助/版权授权）": "sales", "商务（媒体招商）": "sales", "商务（渠道开拓/投标/招商）": "sales",
  "商务拓展（BD）/渠道运营": "sales", "商务造价员（标书/成本分析）": "finance_accounting",
  "商业分析": "data_analysis", "商业分析师": "data_analysis", "商业顾问": "consulting",
  "赏金猎人": "security_emergency", "设备操作员/安全检查员（游乐场）": "operator_production",
  "社工": "counseling", "社会服务工作者": "counseling", "社会活动家": "generic", "社会学家": "research_academic",
  "摄像/音响/灯光设备人员": "media_production", "摄像师": "media_production", "摄影记者": "pr_media_journalist",
  "摄影模特/寄拍模特": "performance_art", "摄影师": "media_production", "神经科医生": "medical_clinical",
  "神经外科医生": "medical_clinical", "神学家": "research_academic", "升学/心理辅导老师": "counseling",
  "生态学家": "research_academic", "生物化学家": "research_academic", "生物技术行业": "generic",
  "生物学家": "research_academic", "生物医学工程师": "engineering_rd", "诗人": "content_writing",
  "施工工人（钢筋/混凝土/水电/吊车司机）": "general_labor", "施工经理": "field_engineer",
  "时尚编辑": "content_writing", "时尚买手/陈列": "design_creative", "时尚行业": "generic",
  "实验室技术员": "lab_tech", "士兵": "security_emergency", "市场策划/文案策划/活动策划": "marketing_ops",
  "市场调研/用户调研": "data_analysis", "市场调研员/市场分析": "data_analysis",
  "市场经营部（套餐设计/营销策划）": "marketing_ops", "市场营销（客运）": "marketing_ops",
  "市场营销经理": "management", "市场专员": "marketing_ops", "市场总监": "management",
  "视频剪辑师": "media_production", "试驾员/品酒师/校对/临床试验员/药事人员": "generic",
  "室内设计师": "design_creative", "室内装饰师": "skilled_trade", "收银员": "retail_clerk",
  "首席执行官": "management", "兽医": "agriculture", "兽医/宠物洗护": "agriculture", "兽医技术员": "agriculture",
  "售货员/店员": "retail_clerk", "售楼处销售": "sales", "售票员/检票服务人员": "customer_service",
  "售前工程师": "sales", "书店老板": "management", "书店老板或店员": "retail_clerk", "书商": "management",
  "数据分析": "data_analysis", "数据分析师": "data_analysis", "数据库管理员": "it_ops",
  "数学家": "research_academic", "数学老师": "teaching", "数字艺术家": "design_creative",
  "水管工": "technician_repair", "水手/船员": "aviation", "司法心理学家": "counseling",
  "私人健身教练": "teaching", "私人银行/家族办公室资产配置": "finance_sales", "私人助理": "hr_admin",
  "特殊教育工作者": "teaching", "特殊教育教师": "teaching", "体育管理行业": "generic",
  "天文学家": "research_academic", "统计学家": "research_academic", "投流": "marketing_ops",
  "投资经理（VC/PE）": "finance_analyst", "投资银行家": "finance_analyst", "图书编辑": "content_writing",
  "图书馆/博物馆/档案馆/美术馆馆员": "librarian_archive", "图书馆员": "librarian_archive",
  "图书馆助理": "librarian_archive", "土木工程师": "engineering_rd", "外交官": "civil_service",
  "外科医生": "medical_clinical", "网络工程师": "it_ops", "网络运维/传输优化": "it_ops",
  "网络专员": "it_ops", "网文作者": "content_writing", "网页开发工程师": "software_dev",
  "网页设计师": "design_creative", "网站管理员": "it_ops", "网站设计师": "design_creative",
  "微生物学家": "research_academic", "维修养护工人/消防监控员": "technician_repair",
  "文案编辑（兴趣电商）": "content_writing", "文案编辑/作者": "content_writing", "文案撰稿人": "content_writing",
  "文创产品设计": "design_creative", "文物修复": "skilled_trade", "文员": "hr_admin",
  "文字编辑/校对": "content_writing", "纹身师": "skilled_trade", "舞蹈老师": "teaching",
  "舞台灯光/音响/烟花技师": "media_production", "舞台技术员": "media_production", "舞台监督": "media_production",
  "舞者": "performance_art", "物理学家": "research_academic", "物理治疗师": "medical_support",
  "物品/仓库管理人员": "logistics_warehouse", "物业招商岗位": "sales", "物资材料员": "logistics_warehouse",
  "喜剧演员": "performance_art", "戏剧导演": "performance_art", "戏剧老师": "teaching", "戏剧行业": "generic",
  "系统分析师": "data_analysis", "系统工程师": "software_dev", "现场执行/艺人选手管理": "pm_product",
  "现场指挥/调度/塔台管制员": "operator_production", "项目经理": "pm_product", "消防员": "security_emergency",
  "销售/店员（ToC）": "sales", "销售经理": "management", "销售员": "sales", "销售专员": "sales",
  "小企业主": "management", "小说家": "content_writing", "小学教师": "teaching", "心理学家": "counseling",
  "心理学研究者": "research_academic", "心理治疗师": "counseling", "心理咨询师": "counseling",
  "心理咨询师/求职咨询师": "counseling", "心脏病医生": "medical_clinical", "新闻记者": "pr_media_journalist",
  "新闻主播": "performance_art", "信贷员": "finance_sales", "信息管理/IT运维": "it_ops",
  "信息技术行业": "generic", "行业研究员（卖方/买方行研）": "finance_analyst", "行政": "hr_admin",
  "行政管理人员": "hr_admin", "行政支持": "hr_admin", "行政助理": "hr_admin", "宣传/传媒对接": "marketing_ops",
  "宣传专员": "marketing_ops", "选角导演": "pm_product", "选品/采购（零售）": "marketing_ops",
  "学前班教师": "childcare", "学校辅导员": "counseling", "学校心理学家": "counseling", "学者": "research_academic",
  "学者/学术人员": "research_academic", "驯马师": "agriculture", "驯兽师": "agriculture",
  "牙科助理": "medical_support", "研发设计工程师（各行业工程师）": "engineering_rd",
  "研究科学家": "research_academic", "研究员": "research_academic", "研究助理": "research_assistant",
  "演艺人员": "performance_art", "演员": "performance_art", "演员/NPC": "performance_art",
  "演员助理/摄影助理": "media_production", "养殖/种植技术员": "agriculture", "摇滚明星": "performance_art",
  "药剂师": "medical_support", "药剂师或药房技术员": "medical_support", "野生动物生物学家": "research_academic",
  "业务经理": "management", "业务员（跑业务/ToB销售/医药代表）": "sales", "业务员/联络员（货运）": "sales",
  "医护人员": "medical_support", "医疗记录员": "medical_support", "医疗行业": "generic",
  "医疗助理": "medical_support", "医生": "medical_clinical", "医生/护士/疾控（医疗事业单位）": "medical_clinical",
  "医生助理": "medical_support", "医学研究员": "research_academic", "遗传学家": "research_academic",
  "遗传学研究员": "research_academic", "艺术策展人": "librarian_archive", "艺术家": "design_creative",
  "艺术教育": "teaching", "艺术教育行业": "generic", "艺术史学家": "research_academic",
  "艺术与传媒行业": "generic", "艺术治疗师": "counseling", "艺术总监": "management",
  "音乐表演者": "performance_art", "音乐记者": "pr_media_journalist", "音乐教育工作者": "teaching",
  "音乐人": "performance_art", "音乐行业": "generic", "音乐制作人": "media_production",
  "音乐制作人/总监": "media_production", "音乐治疗师": "counseling", "音乐DJ": "performance_art",
  "音频工程师": "media_production", "音响工程师": "media_production", "银行柜员": "banking_clerk",
  "银行家": "management", "银行客户经理（对私/对公）": "finance_sales", "印刷/广告制作店员": "retail_clerk",
  "印务": "operator_production", "英语教授": "research_academic", "英语老师": "teaching",
  "营养师": "medical_support", "营养师/康复师": "medical_support", "营业部销售": "finance_sales",
  "影评人": "content_writing", "影视美术/服化道": "media_production", "游戏策划": "pm_product",
  "游戏美术（原画/建模/动画）": "design_creative", "游戏设计师": "design_creative",
  "幼儿教育工作者": "childcare", "幼儿园教师": "childcare", "娱乐法律师": "legal", "娱乐行业": "generic",
  "宇航员": "aviation", "语言学家": "research_academic", "运动训练师": "teaching", "运动医学行业": "generic",
  "运动员": "performance_art", "运维/数据库管理/网络安全": "it_ops", "运行/检修/抢修/电工/水工": "technician_repair",
  "运营（内容/用户/活动）": "marketing_ops", "运营（增长/活动/电商/自媒体/商家运营）": "marketing_ops",
  "运营/市场（媒体）": "marketing_ops", "运营经理": "management", "杂志编辑": "content_writing",
  "造型师": "hospitality", "责任编辑/总编室": "content_writing", "展览/活动策划与销售（主办方）": "pm_product",
  "展览设计师": "design_creative", "战斗机飞行员": "aviation", "战略分析/战略投资": "consulting",
  "战略分析师": "consulting", "哲学家": "research_academic", "哲学教授": "research_academic",
  "政策分析师": "consulting", "政府雇员": "civil_service", "政府职能局（财政/税务/海关等窗口与管理）": "civil_service",
  "政客": "management", "政企事业部（大客户）": "sales", "政治分析员": "consulting",
  "政治学家": "research_academic", "执业护士": "medical_clinical", "职业杀手": "security_emergency",
  "职业摄影师": "media_production", "职业体育运动": "performance_art", "职业学生（继续深造）": "generic",
  "职业音乐人": "performance_art", "植物学家": "research_academic", "植物养护/动物饲养员": "agriculture",
  "制片人": "pm_product", "制片人/主编": "pm_product", "治疗师": "counseling", "主播": "performance_art",
  "主持人（婚庆/活动）": "performance_art", "主厨": "skilled_trade", "主管": "management",
  "助播": "performance_art", "助产士": "medical_support", "装迁与维护维修人员": "technician_repair",
  "装卸人员/设备操作人员": "operator_production", "咨询顾问/分析师/研究员": "consulting",
  "资产管理/自营": "finance_analyst", "自媒体/新媒体运营": "marketing_ops",
  "自然资源/文物/动物保护研究员": "research_academic", "自由艺术家": "design_creative",
  "自由撰稿人": "content_writing", "租赁业务员": "sales", "作家": "content_writing",
  "作曲家": "content_writing", "DJ": "performance_art", "IT从业者": "software_dev",
  "IT服务项目经理/需求分析": "pm_product", "IT顾问": "consulting", "IT经理": "management",
  "QA/测试工程师/试验工程师": "software_dev", "QC质检员/检测员": "lab_tech",
  "UI/UE视觉交互设计": "design_creative",
};
